name: Build and Push Docker Image

on:
  schedule:
    # Runs every day at midnight (00:00 UTC)
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u vishwaravi321 --password-stdin

      # Set environment variables for APPS_JSON
      - name: Set up APPS_JSON environment variable
        run: |
          export APPS_JSON='[
            {
              "url": "https://github.com/frappe/erpnext",
              "branch": "version-15"
            },
            {
              "url": "https://github.com/frappe/payments",
              "branch": "version-15"
            },
            {
              "url":"https://github.com/frappe/hrms",
              "branch":"version-15"
            },
            {
              "url":"https://github.com/resilient-tech/india-compliance",
              "branch":"version-15"
            }
          ]'
          export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0)
          echo "APPS_JSON_BASE64=${APPS_JSON_BASE64}" >> $GITHUB_ENV

      # Build the Docker image with the specified build arguments
      - name: Build Docker image
        run: |
          docker build \
            --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
            --build-arg=FRAPPE_BRANCH=version-15 \
            --build-arg=PYTHON_VERSION=3.11.9 \
            --build-arg=NODE_VERSION=18.20.2 \
            --build-arg=APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }} \
            --tag=ghcr.io/vishwaravi321/erpnext:latest \
            --file=images/custom/Containerfile .

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/vishwaravi321/erpnext:latest
